import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link"
import Navigation from "@/components/Navigation"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <Navigation />
        <div>
          <p>
            Example of using different mechanics for form control
          </p>
          <ul>
            <li>
              <Link href="/react-hook-form">React Hook Form</Link>
            </li>
            <li>
              <Link href="/reducer-form">Reducer Form</Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  )
}
